# Generated by Django 5.2.5 on 2025-11-26 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Ej: webpay, transferencia, tarjeta_mock', unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador interno: basic, pro, etc.', unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_clp', models.PositiveIntegerField(default=0)),
                ('periodo', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('dias_prueba', models.PositiveIntegerField(default=0)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('max_tareas', models.PositiveIntegerField(blank=True, null=True)),
                ('max_tags', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['precio_clp'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('trialing', 'En período de prueba'), ('pending', 'Pendiente de pago'), ('past_due', 'Pago atrasado')], default='trialing', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('proveedor_id', models.CharField(blank=True, help_text='ID de suscripción en el proveedor externo (ficticio por ahora).', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripcion.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_clp', models.PositiveIntegerField()),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('referencia_proveedor', models.CharField(blank=True, help_text='ID/orden que devolvería el proveedor de pago (mock).', max_length=255)),
                ('mensaje_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='suscripcion.metodopago')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripcion.suscripcion')),
            ],
        ),
    ]
