# Generated by Django 5.2.5 on 2025-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusaApp', '0002_perfil_genero_perfil_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
