# Generated by Django 5.2.5 on 2025-11-24 06:08

import focusaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusaApp', '0003_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=focusaApp.models.avatar_upload_path),
        ),
    ]
