# Generated by Django 5.2.5 on 2025-11-24 06:08

import Kanban.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0002_tag_tarea_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=Kanban.models.tarea_attachment_upload_path),
        ),
    ]
